### ISSUE TITLE
Now work with terraform > v.0.11.0

### ISSUE THREAD

**Issue by thunderbird86** [coreos/terraform-aws-tectonic#11] opened 2017-12-03 19:00 UTC
Get error when try to init 
```
- module "container_linux": missing required argument "version"
```
this is fix
```
  source = "github.com/coreos/tectonic-installer//modules/container_linux?ref=0a22c73d39f67ba4bb99106a9e72322a47179736"

  release_channel = "${var.tectonic_container_linux_channel}"
  release_version = "${var.tectonic_container_linux_version}"
```

**Comment by squat** [comment] 2017-12-03 20:54
@thunderbird86 thanks for filing this. This issue is a dupe of https://github.com/coreos/terraform-aws-kubernetes/issues/10#issuecomment-348180774. I fixed the issue upstream in https://github.com/coreos/tectonic-installer/pull/2471. Closing this issue since it is already tracked.

**Closed as completed by squat** 2017-12-03 20:54 UTC
